config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "polls#index"
  put '/polls/:id/saving', :to => 'polls#save', :as => "save_poll"
  resources :polls do
  	resources :questions
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to(:user)	
	belongs_to(:question)	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
	validates(:title, :presence=>true)
	has_many(:questions, :dependent=>:destroy)
end

app/models/question.rb
class Question < ApplicationRecord
	validates(:statement, :presence=>true, :length=>{:minimum=>1, :maximum=>128})
	# questions <=> user 
	has_many(:answers, :dependent=>:destroy)
	has_many(:users, :through=>:answers)
	belongs_to(:poll)
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # users <=> questions
  has_many :answers, :dependent => :destroy
  has_many :questions, :through => :answers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
	before_action :authenticate_user!
	before_action :no_auth, only: [:new, :create, :destroy]


	def index
		@polls = Poll.all
		@user = current_user
	end

	def show
		# print("Timeout", params[:timeout])
		@poll = Poll.find(params[:id])
		@answers = Answer.all
		@user = current_user

	end

	def new
		@poll = Poll.new
		render action: :new
	end

	def create
		@poll = Poll.create(poll_params)
		flash[:notice] = "Poll was successfully created"
  	if @poll.save
			redirect_to(poll_path(@poll))
		else
			render(:action=>:new)
		end
	end

	def destroy
		@poll = Poll.find(params[:id])
		@poll.destroy
		redirect_to(:action=>:index)
	end

	# Save the response
	def save
		@poll = Poll.find(params[:id])
		@user = current_user
		@question = Question.where(statement: params[:choice]).where(poll_id: params[:id]) # return array

		unless params[:choice]
			redirect_to(:action=>:show)
		else
			@answer = Answer.create({:user_id=>@user.id, :question_id=>@question[0].id, :poll_id=>@poll.id})
			redirect_to(:action=>:show)
		end
	end

	private 
	def poll_params
   	params.require(:poll).permit(:title)
  end

  def no_auth
  	unless current_user.admin?
  		redirect_to root_path
  	end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!
	before_action :no_auth

	def new
		@question = Question.new
		@poll = Poll.find(params[:poll_id])
	end

	def create
		@poll = Poll.find(params[:poll_id])
		@question = @poll.questions.create(question_param)

		if @question.save
			redirect_to(poll_path(@poll))
		else
			render(:action => "new")
		end
	end

	def edit
		@poll = Poll.find(params[:poll_id])
		@question = Question.find(params[:id])
	end

	def update
		@poll = Poll.find(params[:poll_id])
		@question = Question.find(params[:id])
		@question.update(question_param)
		if @question.save
			redirect_to(poll_path(@poll))
		else
			render(:action => "edit")
		end
	end

	def destroy
		@poll = Poll.find(params[:poll_id])
		@question = @poll.questions.find(params[:id])
		@question.destroy
		redirect_to(:controller=>:polls, :action=>:show, :id=>params[:poll_id])
	end

	private

	def question_param
		params.require(:question).permit(:statement)
	end

	def no_auth
  	unless current_user.admin?
  		redirect_to root_path
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PollingSystemV2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
  	<div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= link_to "Home", root_path %> | 
      <% if current_user %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/polls/_result.html.erb
<div id='result'>
    <h2>Result</h2>
    <% @poll.questions.each do |q| %>
        <p><%= q.statement + ":" + @answers.where(question_id: q.id).size.to_s %></p>
        <p>
        <% q.users.includes(:answers).where('answers.poll_id = ?', @poll.id).each do |u| %>
            <%= u.email %>
        <% end %>
        </p>
    <% end %>
</div>

app/views/polls/index.html.erb
<h1>Polls list</h1>
<% @polls.each do |p| %>
	<table>
		<tr>
			<td><%= link_to p.title, poll_path(p) %> </td>
            <% if @user.admin? %>
			<td><%= link_to "Delete", poll_path(p), method: "delete",data: { confirm: 'Are you sure?' } %></td>
            <% end %>
		</tr>
	</table>
<% end %>
<% if @polls.size == 0 %>
	<em>No polls found</em>
<% end %>

<% if @user.admin? %>
    </br>
    <%= link_to "Create a new Poll", new_poll_path %>
<% end %>

app/views/polls/new.html.erb
<h1>New Poll</h1>
<%= form_for(@poll, :url => {:controller=>"polls", :action=>"create" }) do |p| %>
	<%= p.label :title, "Poll Title" %>
	<%= p.text_field :title %><br />
	<%= p.submit "Create a Poll"%>
<% end %>

app/views/polls/show.html.erb
<h1><%= @poll.title %></h1>

<% if @user.admin? %>
	<%= link_to("Add a question", new_poll_question_path(@poll)) %></br></br>
<% end %>

<% unless @user.answers.where(poll_id: @poll.id).first %>
	<div id='choice_form'>
		<%= form_tag({controller: "polls", action: "save", id: @poll.id}, method: :put) do %>	
			<% @poll.questions.each do |q| %>
				<%= radio_button_tag "choice", q.statement %>
				<%= q.statement %>
				<% if @user.admin? %>
					<%= link_to "Edit", edit_poll_question_path(@poll, q) %>

					<%= link_to "Delete", poll_question_path(@poll, q), method: "delete", data: {:confirm=>"Are you sure you want to delete? "} %>
				<% end %>
				</br>
			<% end %>
			<%= submit_tag("Save") %>
		<% end %>
	</div>
	<div id='show_result' style='display:none'>
		<%= render :partial => "result" %>
	</div>
<% else %>
	<strong>Voted</strong>
	<%= render :partial => "result" %>
<% end %>

<script type="text/javascript">
	setTimeout(function(){
		$('#show_result').slideUp('slow').show(function(){
			$('#choice_form').slideUp('slow').fadeOut()
		});
	}, 10000);
</script>

app/views/questions/edit.html.erb
<%= form_for @question, :url => {:controller=>"questions", :action => "update", :poll_id => @poll.id, :id => @question.id}, :method => :patch do |q| %>
    <%= q.label :statement, "Statement: " %>
    <%= q.text_field :statement %>
    <%= q.submit %>
<% end %>

app/views/questions/new.html.erb
<%= form_for(@question, url: { controller: "questions", action: "create", poll_id: @poll.id } ) do |q| %>
	<%= q.label :statement, "Statement: " %>
	<%= q.text_field :statement %>
	<%= q.submit %>
<% end %>